### ISSUE TITLE
후원을 처리중입니다. 잠시만 기다려주세요... 에서 작동을 안합니다, 해당 코드에 문제 있는지 확인 해주실 수 있으실까요?

### ISSUE THREAD

**Issue by rc0n9027** [MinecraftTorch/TorchDonation#2]
JDK14 사용 중입니다!

org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="wrap"]/div[1]/section/dl/dd"}
  (Session info: headless chrome=99.0.4844.84)

**Comment by isu-kim** [comment]
기존 코드의 경우 `[@id="wrap"]/div[1]/section/dl/dd"` 과 `[@id="wrap"]/div[4]/section/dl/dd"` 만 탐지해서 생기는 오류로 확인되어서 이를 수정했습니다. https://gooday2die.net/TorchDonation 에서 파일을 다운받으시면 되겠습니다. 혹시 또 오류가 생긴다면 말씀해주시면 더 수정해보겠습니다.
