### ISSUE TITLE
현재 시스템이 작동하지 않습니다.

### ISSUE THREAD

**Issue by LIBIBKK** [MinecraftTorch/TorchDonation#3]
테스트 해보니까 로그인에서 실패가 되는군요. 아이디 비번 모두 일치한데도 불구하구요. 확인 가능할까요?

**Comment by isu-kim** [comment]
Stack Trace 를 첨부해주시면 감사하겠습니다.

**Comment by koza-d** [comment]
확인해보니 캡챠때문에 막히는 거 같습니다.

**Comment by isu-kim** [comment]
@dkrlrha1240 사실은 컬쳐랜드 플러그인 이외에 만들어진 컬쳐랜드 충전 [파이썬 라이브러리](https://github.com/gooday2die/CulturelandPython)에는 캡챠를 풀 수 있게 해놓았습니다. 하지만 사용하는 방법이 Anti-Captcha 사의 API 를 사용합니다. 일반적으로 이 플러그인 사용하시는 유저분들께서 해당 API 발급 받는것과 Anti-Captcha 사의 계정에 돈을 먼저 충전해놓는 것이 조금 번거로울 것 같기에 자체적으로 캡챠를 뚫는 방안을 구현중입니다. 그래서 일단 이 플러그인은 아직 업데이트 대기중입니다...

+ 컬쳐랜드의 눈치가 살살 보이는 것도 없지 않아 있구요...
